# Generated by Django 3.2.8 on 2021-10-26 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Technology Name')),
                ('company', models.CharField(max_length=150, verbose_name='Company Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('company_address', models.CharField(max_length=50, verbose_name='Company Address')),
                ('short_description', models.CharField(max_length=250, verbose_name='Short details')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_posted', models.DateTimeField(verbose_name='Date Posted')),
                ('upvotes', models.IntegerField(default=0)),
                ('main_photo', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='Upload Image')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
