# Generated by Django 3.2.8 on 2021-10-28 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_alter_technology_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Technology Name')),
                ('company', models.CharField(max_length=150, verbose_name='Company Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_requested', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Requested')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='technologies.technology')),
            ],
        ),
    ]
