# Generated by Django 3.2.8 on 2021-10-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_requested',
        ),
    ]
