# Generated by Django 3.2.8 on 2021-10-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0005_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
