# Generated by Django 3.2.8 on 2021-10-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0006_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('-date_posted',)},
        ),
    ]
